/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFrame;

import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.mysql.jdbc.Statement;

import connect.MysqlConnection;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author D2J
 */
public class formJenis extends javax.swing.JFrame {

    /**
     * Creates new form formJenis
     */
    public formJenis() {
        initComponents();
        datatable();
        mati();
        btn_tambah.setEnabled(true);
        btn_simpan.setEnabled(false);
        btn_edit.setEnabled(false);
        btn_hapus.setEnabled(false);
        btn_batal.setEnabled(false);
        btn_keluar.setEnabled(true);
    }

    private void mati() {
    	txt_jenis.setEnabled(false);
    	txt_hargasewa.setEnabled(false);
    	btn_tambah.setEnabled(true);
    	btn_simpan.setEnabled(false);
        btn_batal.setEnabled(false);
        btn_keluar.setEnabled(true);
    }
    
    private void hidup() {
    	txt_jenis.setEnabled(true);
    	txt_hargasewa.setEnabled(true);
    	txt_jenis.requestFocus();
    }
    
    private void bersih() {
    	txt_jenis.setText("");
    	txt_hargasewa.setText("");
    }

    private void datatable() {
    	DefaultTableModel tbl = new DefaultTableModel();
    	tbl.addColumn("Jenis");
    	tbl.addColumn("Harga Sewa");
    	tbl_kelfilm.setModel(tbl);
    	try {
    		Statement statement = (Statement)MysqlConnection.GetConnection().createStatement();
    		ResultSet res=statement.executeQuery("select * from pbo_kelfilm");
    		while (res.next())
    		{tbl.addRow(new Object[]{
    			res.getString("jenis"),
    			res.getString("harga_sewa")
    		});
    		tbl_kelfilm.setModel(tbl);
    		}
    	}catch (Exception e) {
    		JOptionPane.showMessageDialog(rootPane, "Salah di Tabel Data");
    	}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_jenis = new javax.swing.JTextField();
        txt_hargasewa = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JButton();
        btn_tambah.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		hidup();
        		bersih();
        		btn_tambah.setEnabled(false);
        		btn_simpan.setEnabled(true);
        		btn_edit.setEnabled(false);
        		btn_hapus.setEnabled(false);
        		btn_batal.setEnabled(true);
        		btn_keluar.setEnabled(true);
        	}
        });
        btn_simpan = new javax.swing.JButton();
        btn_simpan.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String jenis = txt_jenis.getText();
        		String harga = txt_hargasewa.getText();
        		try{
        			 Statement statement = (Statement) MysqlConnection.GetConnection().createStatement();
        			 statement.executeUpdate("insert into pbo_kelfilm VALUES ('"+jenis+"', '"+harga+"')"); 
        			 statement.close();
        			 JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
        		 }catch(Exception t){
        			 JOptionPane.showMessageDialog(null,"Data Gagal Disimpan");
        		 }
        		 datatable();
        		 mati();
        	}
        });
        btn_edit = new javax.swing.JButton();
        btn_edit.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String jenis = txt_jenis.getText();
        		String harga = txt_hargasewa.getText();
        		
        		try {
        			Statement statement = (Statement) MysqlConnection.GetConnection().createStatement();
        			statement.executeUpdate("UPDATE pbo_kelfilm SET jenis = '"+jenis+"', harga_sewa = '"+harga+"' where jenis = '"+jenis+"'");
        			
        		JOptionPane.showMessageDialog(null, "Data Berhasil Diubah!");
        		}catch(Exception t){
        			JOptionPane.showMessageDialog(null, "Data Gagal Diubah!");
        		}
        		datatable();
        	}
        });
        btn_hapus = new javax.swing.JButton();
        btn_hapus.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String jenis = txt_jenis.getText();
        		
        		try {
        			Statement statement = (Statement) MysqlConnection.GetConnection().createStatement();
        			statement.executeUpdate("DELETE from pbo_kelfilm where jenis = ('"+jenis+"')");
        			JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus!");
        			txt_jenis.setText("");
        			txt_hargasewa.setText("");
        		}catch(Exception t){
        			JOptionPane.showMessageDialog(null, "Data Gagal di Hapus");
        		}
        		datatable();
        	}
        });
        btn_batal = new javax.swing.JButton();
        btn_batal.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		bersih();
        		btn_tambah.setEnabled(true);
        		btn_simpan.setEnabled(false);
        		btn_edit.setEnabled(false);
        		btn_hapus.setEnabled(false);
        		btn_batal.setEnabled(false);
        		btn_keluar.setEnabled(true);
            	txt_jenis.setEnabled(false);
            	txt_hargasewa.setEnabled(false);
        	}
        });
        btn_keluar = new javax.swing.JButton();
        btn_keluar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        	}
        });
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_kelfilm = new javax.swing.JTable();
        tbl_kelfilm.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		hidup();
        		int row=tbl_kelfilm.getSelectedRow();
        		txt_jenis.setText((String)tbl_kelfilm.getValueAt(row, 0));
        		txt_hargasewa.setText((String)tbl_kelfilm.getValueAt(row, 1));
        		btn_tambah.setEnabled(false);
        		btn_edit.setEnabled(true);
        		btn_hapus.setEnabled(true);
        		btn_batal.setEnabled(true);
        		btn_simpan.setEnabled(false);
       			txt_jenis.setEditable(false);
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Kelompok Film");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Jenis Film");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Harga Sewa");

        btn_tambah.setText("Tambah");

        btn_simpan.setText("Simpan");

        btn_edit.setText("Edit");

        btn_hapus.setText("Hapus");

        btn_batal.setText("Batal");

        btn_keluar.setText("Keluar");

        tbl_kelfilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_kelfilm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_hargasewa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_hargasewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formJenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formJenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formJenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formJenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formJenis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_kelfilm;
    private javax.swing.JTextField txt_hargasewa;
    private javax.swing.JTextField txt_jenis;
    // End of variables declaration//GEN-END:variables
}
