/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFrame;

import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.mysql.jdbc.Statement;

import connect.MysqlConnection;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.DefaultComboBoxModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;

/**
 *
 * @author D2J
 */
public class formFilm extends javax.swing.JFrame {

    /**
     * Creates new form formFilm
     */
    public formFilm() {
        initComponents();
        datatable();
        mati();
        updateCmb();
        btn_tambah.setEnabled(true);
        btn_simpan.setEnabled(false);
        btn_edit.setEnabled(false);
        btn_hapus.setEnabled(false);
        btn_keluar.setEnabled(true);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel6);
        getContentPane().add(jLabel3);
        getContentPane().add(txt_judul);
        getContentPane().add(jLabel1);
        getContentPane().add(jLabel2);
        getContentPane().add(txt_kode);
        getContentPane().add(cmb_jenis);
        getContentPane().add(jLabel5);
        getContentPane().add(txt_jmlfilm);
        getContentPane().add(jLabel4);
        getContentPane().add(txt_jmlkeping);
        getContentPane().add(btn_tambah);
        getContentPane().add(btn_simpan);
        getContentPane().add(btn_edit);
        getContentPane().add(btn_hapus);
        getContentPane().add(btn_keluar);
        getContentPane().add(jScrollPane1);
        getContentPane().add(btn_batal);
    }
    
    private void mati() {
    	txt_kode.setEnabled(false);
    	txt_judul.setEnabled(false);
    	cmb_jenis.setEnabled(false);
    	txt_jmlfilm.setEnabled(false);
    	txt_jmlkeping.setEnabled(false);
    }
    
    private void hidup() {
    	txt_kode.setEnabled(true);
    	txt_judul.setEnabled(true);
    	cmb_jenis.setEnabled(true);
    	txt_jmlfilm.setEnabled(true);
    	txt_jmlkeping.setEnabled(true);
    	txt_kode.requestFocus();
    }
    
    private void bersih() {
    	txt_kode.setText("");
    	txt_judul.setText("");
    	cmb_jenis.setSelectedItem("");
    	txt_jmlfilm.setText("");
    	txt_jmlkeping.setText("");   
    }

    private void datatable() {
    	DefaultTableModel tbl = new DefaultTableModel();
    	tbl.addColumn("Kode Film");
    	tbl.addColumn("Judul");
    	tbl.addColumn("Jumlah Keping");
    	tbl.addColumn("Jumlah Film");
    	tbl.addColumn("Jenis");
    	tbl_film.setModel(tbl);
    	try {
    		Statement statement = (Statement)MysqlConnection.GetConnection().createStatement();
    		ResultSet res=statement.executeQuery("select * from pbo_film");
    		while (res.next())
    		{tbl.addRow(new Object[]{
    			res.getString("kode_film"),
    			res.getString("judul"),
    			res.getString("jml_keping"),
    			res.getString("jml_film"),
    			res.getString("jenis")
    		});
    		tbl_film.setModel(tbl);
    		}
    	}catch (Exception e) {
    		JOptionPane.showMessageDialog(rootPane, "Salah di Tabel Data");
    	}
    }
    
    private void updateCmb() {
    	try {
    		Statement pst = (Statement)MysqlConnection.GetConnection().createStatement();
    		ResultSet rs = pst.executeQuery("select * from pbo_kelfilm");
    		while(rs.next()) {
    			cmb_jenis.addItem(rs.getString("jenis"));
    		}
    	}catch(Exception e){
    		
    	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setBounds(10, 46, 71, 14);
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setBounds(10, 81, 71, 14);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setBounds(10, 122, 52, 14);
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setBounds(10, 168, 103, 14);
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setBounds(10, 209, 105, 14);
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setBounds(181, 10, 74, 22);
        txt_kode = new javax.swing.JTextField();
        txt_kode.setBounds(123, 43, 95, 22);
        txt_judul = new javax.swing.JTextField();
        txt_judul.setBounds(123, 114, 213, 31);
        cmb_jenis = new javax.swing.JComboBox<>();
        cmb_jenis.setBounds(123, 74, 105, 29);
        txt_jmlfilm = new javax.swing.JTextField();
        txt_jmlfilm.setBounds(125, 201, 36, 31);
        txt_jmlkeping = new javax.swing.JTextField();
        txt_jmlkeping.setBounds(123, 161, 38, 29);
        btn_batal = new JButton("Batal");
        btn_batal.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		bersih();
        		btn_tambah.setEnabled(true);
        		btn_simpan.setEnabled(false);
        		btn_edit.setEnabled(false);
        		btn_hapus.setEnabled(false);
        		btn_batal.setEnabled(false);
        		btn_keluar.setEnabled(true);
            	txt_kode.setEnabled(false);
            	txt_judul.setEnabled(false);
            	cmb_jenis.setEnabled(false);
            	txt_jmlkeping.setEnabled(false);
            	txt_jmlfilm.setEnabled(false);
        	}
        });
        btn_batal.setBounds(339, 253, 74, 31);
        btn_tambah = new javax.swing.JButton();
        btn_tambah.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		hidup();
        		bersih();
        		btn_tambah.setEnabled(false);
        		btn_simpan.setEnabled(true);
        		btn_edit.setEnabled(false);
        		btn_hapus.setEnabled(false);
        		btn_batal.setEnabled(true);
        		btn_keluar.setEnabled(true);
        	}
        });
        btn_tambah.setBounds(7, 253, 74, 31);
        btn_simpan = new javax.swing.JButton();
        btn_simpan.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String nmr = txt_kode.getText();
        		String jenis = (String) cmb_jenis.getSelectedItem();
        		String judul = txt_judul.getText();
        		String jmlk = txt_jmlkeping.getText();
        		String jmlf = txt_jmlfilm.getText();
        		 try {
        			 Statement statement = (Statement) MysqlConnection.GetConnection().createStatement();
        			 statement.executeUpdate("insert into pbo_film VALUES ('"+nmr+"', '"+judul+"', '"+jmlk+"', '"+jmlf+"', '"+jenis+"')"); 
        			 statement.close();
        			 JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
        		 }catch(Exception t){
        			 JOptionPane.showMessageDialog(null,"Data Gagal Disimpan");
        		 }
        		 datatable();
        	}
        });
        btn_simpan.setBounds(87, 253, 74, 31);
        btn_edit = new javax.swing.JButton();
        btn_edit.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String nmr = txt_kode.getText();
        		String jenis = (String) cmb_jenis.getSelectedItem();
        		String judul = txt_judul.getText();
        		String jmlk = txt_jmlkeping.getText();
        		String jmlf = txt_jmlfilm.getText();
        		
        		try {
        			Statement statement = (Statement) MysqlConnection.GetConnection().createStatement();
        			statement.executeUpdate("UPDATE pbo_film SET kode_film = '"+nmr+"', judul = '"+judul+"', jml_keping = '"+jmlk+"', jml_film = '"+jmlf+"', jenis = '"+jenis+"' WHERE kode_film = '"+nmr+"'");
        			
        		JOptionPane.showMessageDialog(null, "Data Berhasil Diubah!");
        		}catch(Exception t){
        			JOptionPane.showMessageDialog(null, "Data Gagal Diubah!");
        		}
        		datatable();
        	}
        });
        btn_edit.setBounds(171, 253, 74, 31);
        btn_hapus = new javax.swing.JButton();
        btn_hapus.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String nmr = txt_kode.getText();
        		
        		try {
        			Statement statement = (Statement) MysqlConnection.GetConnection().createStatement();
        			statement.executeUpdate("DELETE from pbo_film where kode_film = ('"+nmr+"')");
        			JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus!");
        			txt_judul.setText("");
        			txt_jmlkeping.setText("");
        			cmb_jenis.setSelectedItem("Sci-Fi");
        			txt_kode.setText("");
        			txt_jmlfilm.setText("");
        		}catch(Exception t){
        			JOptionPane.showMessageDialog(null, "Data Gagal di Hapus");
        		}
        		datatable();
        	}
        });
        btn_hapus.setBounds(255, 253, 74, 31);
        btn_keluar = new javax.swing.JButton();
        btn_keluar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        	}
        });
        btn_keluar.setBounds(423, 253, 74, 31);
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setBounds(10, 295, 478, 95);
        tbl_film = new javax.swing.JTable();
        tbl_film.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		hidup();
        		int row=tbl_film.getSelectedRow();
        		txt_kode.setText((String)tbl_film.getValueAt(row, 0));
        		txt_judul.setText((String)tbl_film.getValueAt(row, 1));
        		txt_jmlkeping.setText((String)tbl_film.getValueAt(row, 2));
        		txt_jmlfilm.setText((String)tbl_film.getValueAt(row, 3));
        		cmb_jenis.setSelectedItem((String)tbl_film.getValueAt(row, 4));
        		btn_tambah.setEnabled(false);
        		btn_edit.setEnabled(true);
        		btn_hapus.setEnabled(true);
        		btn_simpan.setEnabled(false);
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(514, 440));

        jLabel1.setText("Kode Film");

        jLabel2.setText("Jenis Film");

        jLabel3.setText("Judul");

        jLabel4.setText("Jumlah Keping");

        jLabel5.setText("Jumlah Film");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Data Film");


        btn_tambah.setText("Tambah");

        btn_simpan.setText("Simpan");

        btn_edit.setText("Edit");

        btn_hapus.setText("Hapus");

        btn_keluar.setText("Keluar");

        tbl_film.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_film);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> cmb_jenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_film;
    private javax.swing.JTextField txt_jmlfilm;
    private javax.swing.JTextField txt_jmlkeping;
    private javax.swing.JTextField txt_judul;
    private javax.swing.JTextField txt_kode;
    private JButton btn_batal;
}
