/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFrame;

import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import connect.MysqlConnection;
import javax.swing.DefaultComboBoxModel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class formCustomer extends javax.swing.JFrame {

    /**
     * Creates new form formCustomer
     */
    public formCustomer() {
        initComponents();
        datatable();
        mati();
        btn_tambah.setEnabled(true);
        btn_simpan.setEnabled(false);
        btn_edit.setEnabled(false);
        btn_hapus.setEnabled(false);
        btn_batal.setEnabled(false);
        btn_keluar.setEnabled(true);
    }
    
    private void mati() {
    	txt_nama.setEnabled(false);
    	txt_alamat.setEnabled(false);
    	cmb_jenis.setEnabled(false);
    	txt_id.setEnabled(false);
    	txt_telp.setEnabled(false);
    }
    
    private void hidup() {
    	txt_nama.setEnabled(true);
    	txt_alamat.setEnabled(true);
    	cmb_jenis.setEnabled(true);
    	txt_id.setEnabled(true);
    	txt_telp.setEnabled(true);
    	txt_id.requestFocus();
    }
    
    private void bersih() {
    	txt_nama.setText("");
    	txt_alamat.setText("");
    	cmb_jenis.setSelectedItem("");
    	txt_id.setText("");
    	txt_telp.setText("");   
    }

    private void datatable() {
    	DefaultTableModel tbl = new DefaultTableModel();
    	tbl.addColumn("No Identitas");
    	tbl.addColumn("Jenis Identitas");
    	tbl.addColumn("Nama Customer");
    	tbl.addColumn("Alamat");
    	tbl.addColumn("No Telp");
    	tbl_customer.setModel(tbl);
    	try {
    		Statement statement = (Statement)MysqlConnection.GetConnection().createStatement();
    		ResultSet res=statement.executeQuery("select * from pbo_customer");
    		while (res.next())
    		{tbl.addRow(new Object[]{
    			res.getString("id"),
    			res.getString("jenis_id"),
    			res.getString("nama"),
    			res.getString("alamat"),
    			res.getString("no_telp")
    		});
    		tbl_customer.setModel(tbl);
    		}
    	}catch (Exception e) {
    		JOptionPane.showMessageDialog(rootPane, "Salah di Tabel Data");
    	}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_telp = new javax.swing.JTextField();
        cmb_jenis = new javax.swing.JComboBox<>();
        btn_tambah = new javax.swing.JButton();
        btn_tambah.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		hidup();
        		bersih();
        		btn_tambah.setEnabled(false);
        		btn_simpan.setEnabled(true);
        		btn_edit.setEnabled(false);
        		btn_hapus.setEnabled(false);
        		btn_batal.setEnabled(true);
        		btn_keluar.setEnabled(true);
        	}
        });
        btn_edit = new javax.swing.JButton();
        btn_edit.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String nmr = txt_id.getText();
        		String identitas = (String) cmb_jenis.getSelectedItem();
        		String nama = txt_nama.getText();
        		String alamat = txt_alamat.getText();
        		String no_telp = txt_telp.getText();
        		
        		try {
        			Statement statement = (Statement) MysqlConnection.GetConnection().createStatement();
        			statement.executeUpdate("UPDATE pbo_customer SET jenis_id = '"+identitas+"', nama = '"+nama+"', alamat = '"+alamat+"', no_telp = '"+no_telp+"' WHERE id = '"+nmr+"'");
        			
        		JOptionPane.showMessageDialog(null, "Data Berhasil Diubah!");
        		}catch(Exception t){
        			JOptionPane.showMessageDialog(null, "Data Gagal Diubah!");
        		}
        		datatable();
        		
        	}
        });
        btn_hapus = new javax.swing.JButton();
        btn_hapus.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String nmr = txt_id.getText();
        		
        		try {
        			Statement statement = (Statement) MysqlConnection.GetConnection().createStatement();
        			statement.executeUpdate("DELETE from pbo_customer where id = ('"+nmr+"')");
        			JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus!");
        			txt_nama.setText("");
        			txt_alamat.setText("");
        			cmb_jenis.setSelectedItem("KTP");
        			txt_id.setText("");
        			txt_telp.setText("");
        		}catch(Exception t){
        			JOptionPane.showMessageDialog(null, "Data Gagal di Hapus");
        		}
        		datatable();
        	}
        });
        btn_batal = new javax.swing.JButton();
        btn_batal.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		bersih();
        		btn_tambah.setEnabled(true);
        		btn_simpan.setEnabled(false);
        		btn_edit.setEnabled(false);
        		btn_hapus.setEnabled(false);
        		btn_batal.setEnabled(false);
        		btn_keluar.setEnabled(true);
            	txt_nama.setEnabled(false);
            	txt_alamat.setEnabled(false);
            	cmb_jenis.setEnabled(false);
            	txt_id.setEnabled(false);
            	txt_telp.setEnabled(false);
        		
        	}
        });
        btn_keluar = new javax.swing.JButton();
        btn_keluar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        	}
        });
        btn_simpan = new javax.swing.JButton();
        btn_simpan.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String nmr = txt_id.getText();
        		String identitas = (String) cmb_jenis.getSelectedItem();
        		String nama = txt_nama.getText();
        		String alamat = txt_alamat.getText();
        		String no_telp = txt_telp.getText();
        		 try {
        			 Statement statement = (Statement) MysqlConnection.GetConnection().createStatement();
        			 statement.executeUpdate("insert into pbo_customer VALUES ('"+nmr+"', '"+identitas+"', '"+nama+"', '"+alamat+"', '"+no_telp+"')"); 
        			 statement.close();
        			 JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
        		 }catch(Exception t){
        			 JOptionPane.showMessageDialog(null,"Data Gagal Disimpan");
        		 }
        		 datatable();
        	}
        });
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_customer = new javax.swing.JTable();
        tbl_customer.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		hidup();
        		int row=tbl_customer.getSelectedRow();
        		txt_id.setText((String)tbl_customer.getValueAt(row, 0));
        		cmb_jenis.setSelectedItem((String)tbl_customer.getValueAt(row, 1));
        		txt_nama.setText((String)tbl_customer.getValueAt(row, 2));
        		txt_alamat.setText((String)tbl_customer.getValueAt(row, 3));
        		txt_telp.setText((String)tbl_customer.getValueAt(row, 4));
        		btn_tambah.setEnabled(false);
        		btn_edit.setEnabled(true);
        		btn_hapus.setEnabled(true);
        		btn_batal.setEnabled(true);
        		btn_simpan.setEnabled(false);
        		txt_id.setEditable(false);
        	}
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Jenis ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Alamat");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Telp");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("FORM CUSTOMER");

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        cmb_jenis.setModel(new DefaultComboBoxModel(new String[] {"KTP", "SIM", "Lainnya"}));

        btn_tambah.setText("Tambah");

        btn_edit.setText("Edit");

        btn_hapus.setText("Hapus");

        btn_batal.setText("Batal");
        btn_batal.setPreferredSize(new java.awt.Dimension(63, 23));

        btn_keluar.setText("Keluar");

        btn_simpan.setText("Simpan");

        tbl_customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_customer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(39, 39, 39)
                                            .addComponent(txt_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(21, 21, 21)
                                        .addComponent(cmb_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(51, 51, 51)
                                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(33, 33, 33)
                                        .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmb_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> cmb_jenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbl_customer;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_telp;
    // End of variables declaration//GEN-END:variables
}
